global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "tolerex-leader"
    static_configs:
      - targets: ["leader:9090"]
        labels: {role: leader}

  - job_name: "tolerex-members"
    static_configs:
      - targets:
          - "member1:9092"
          - "member2:9093"
          - "member3:9094"
        labels: {role: member}
