global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'tolerex-cluster'
    static_configs:
      - targets:
        # Docker Service Names (Internal DNS)
        - 'leader:9090'
        - 'member-1:9092'
        - 'member-2:9093'
        - 'member-3:9094'
        # Localhost fallbacks (if running outside docker on host network)
        # - 'host.docker.internal:9090' 
